/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.2.qualifier.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by Voice CodeGen Version: Beta_R1_v0.1.0
* generated on: Thu Sep 10 18:55:35 IST 2015
*/
#ifndef COM_HARMAN_VOICE_Arrays_3_PROXY_BASE_HPP_
#define COM_HARMAN_VOICE_Arrays_3_PROXY_BASE_HPP_

#include <v0_1/com/harman/voice/Arrays_3.hpp>



#if !defined (COMMONAPI_INTERNAL_COMPILATION)
#define COMMONAPI_INTERNAL_COMPILATION
#endif

#include <CommonAPI/Deployment.hpp>
#include <CommonAPI/InputStream.hpp>
#include <CommonAPI/OutputStream.hpp>
#include <CommonAPI/Struct.hpp>
#include <cstdint>
#include <vector>

#include <CommonAPI/Proxy.hpp>
#include <functional>
#include <future>

#undef COMMONAPI_INTERNAL_COMPILATION

namespace v0_1 {
namespace com {
namespace harman {
namespace voice {

class Arrays_3ProxyBase
    : virtual public CommonAPI::Proxy {
public:

    typedef std::function<void(const CommonAPI::CallStatus&, const std::vector<Arrays_3::latlong>&)> RouteAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const std::vector<Arrays_3::latlong>&)> GetShortestRouteAsyncCallback;
    typedef std::function<void(const CommonAPI::CallStatus&, const Arrays_3::POIS_NAME&)> GetPOIAsyncCallback;



    virtual void route(const std::vector<Arrays_3::latlong> &_latLong, CommonAPI::CallStatus &_status, std::vector<Arrays_3::latlong> &_path, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> routeAsync(const std::vector<Arrays_3::latlong> &_latLong, RouteAsyncCallback _callback, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void getShortestRoute(const Arrays_3::latlong &_latLongStructure, CommonAPI::CallStatus &_status, std::vector<Arrays_3::latlong> &_path, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getShortestRouteAsync(const Arrays_3::latlong &_latLongStructure, GetShortestRouteAsyncCallback _callback, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual void getPOI(const Arrays_3::latlong &_latLongStruct, CommonAPI::CallStatus &_status, Arrays_3::POIS_NAME &_poisName, const CommonAPI::CallInfo *_info = nullptr) = 0;
    virtual std::future<CommonAPI::CallStatus> getPOIAsync(const Arrays_3::latlong &_latLongStruct, GetPOIAsyncCallback _callback, const CommonAPI::CallInfo *_info = nullptr) = 0;
};

} // namespace voice
} // namespace harman
} // namespace com
} // namespace v0_1

#endif // COM_HARMAN_VOICE_Arrays_3_PROXY_BASE_HPP_
