/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.2.qualifier.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by Voice CodeGen Version: Beta_R1_v0.1.0
* generated on: Thu Sep 10 18:55:35 IST 2015
*/
#ifndef COM_HARMAN_VOICE_Arrays_3_STUB_DEFAULT_HPP_
#define COM_HARMAN_VOICE_Arrays_3_STUB_DEFAULT_HPP_


#include <v0_1/com/harman/voice/Arrays_3Stub.hpp>
#include <sstream>

namespace v0_1 {
namespace com {
namespace harman {
namespace voice {

/**
 * Provides a default implementation for Arrays_3StubRemoteEvent and
 * Arrays_3Stub. Method callbacks have an empty implementation,
 * remote set calls on attributes will always change the value of the attribute
 * to the one received.
 *
 * Override this stub if you only want to provide a subset of the functionality
 * that would be defined for this service, and/or if you do not need any non-default
 * behaviour.
 */
class Arrays_3StubDefault
    : public virtual Arrays_3Stub {
public:
    Arrays_3StubDefault();

    Arrays_3StubRemoteEvent* initStubAdapter(const std::shared_ptr<Arrays_3StubAdapter> &_adapter);

    const CommonAPI::Version& getInterfaceVersion(std::shared_ptr<CommonAPI::ClientId> _client);


    virtual void route(const std::shared_ptr<CommonAPI::ClientId> _client, std::vector<Arrays_3::latlong> _latLong, routeReply_t _reply);
    virtual void getShortestRoute(const std::shared_ptr<CommonAPI::ClientId> _client, Arrays_3::latlong _latLongStructure, getShortestRouteReply_t _reply);
    virtual void getPOI(const std::shared_ptr<CommonAPI::ClientId> _client, Arrays_3::latlong _latLongStruct, getPOIReply_t _reply);



protected:
    class RemoteEventHandler: public virtual Arrays_3StubRemoteEvent {
    public:
        RemoteEventHandler(Arrays_3StubDefault *_defaultStub);


    private:
        Arrays_3StubDefault *defaultStub_;
    };
private:
    Arrays_3StubDefault::RemoteEventHandler remoteEventHandler_;


    CommonAPI::Version interfaceVersion_;
};

} // namespace voice
} // namespace harman
} // namespace com
} // namespace v0_1

#endif // COM_HARMAN_VOICE_Arrays_3_STUB_DEFAULT
