/*
* This file was generated by the CommonAPI Generators.
* Used org.genivi.commonapi.core 3.1.2.qualifier.
* Used org.franca.core 0.9.1.201412191134.
*
* generated by Voice CodeGen Version: Beta_R1_v0.1.0
* generated on: Thu Sep 10 18:55:35 IST 2015
*/
#include "Arrays_3.hpp"

namespace v0_1 {
namespace com {
namespace harman {
namespace voice {



bool Arrays_3::latlong::operator==(const Arrays_3::latlong& _other) const {
	return (getLat() == _other.getLat() && getLongitude() == _other.getLongitude());
}


} // namespace voice
} // namespace harman
} // namespace com
} // namespace v0_1
