/**
 * generated by Voice CodeGen Version: Beta_R1_v0.1.0
 * generated on: Thu Sep 10 18:55:36 IST 2015
 */

#include "v0_1/com/harman/voice/Arrays_3StubImpl.hpp"

namespace v0_1 {
namespace com {
namespace harman {
namespace voice {

Arrays_3StubImpl::Arrays_3StubImpl()
{

}

Arrays_3StubImpl::~Arrays_3StubImpl()
{

}

void Arrays_3StubImpl::route(const std::shared_ptr<CommonAPI::ClientId> _client, std::vector<::v0_1::com::harman::voice::Arrays_3::latlong> latLong, routeReply_t reply)
{
	// TODO: Implement me
}

void Arrays_3StubImpl::getShortestRoute(const std::shared_ptr<CommonAPI::ClientId> _client, ::v0_1::com::harman::voice::Arrays_3::latlong latLongStructure, getShortestRouteReply_t reply)
{
	// TODO: Implement me
}

void Arrays_3StubImpl::getPOI(const std::shared_ptr<CommonAPI::ClientId> _client, ::v0_1::com::harman::voice::Arrays_3::latlong latLongStruct, getPOIReply_t reply)
{
	// TODO: Implement me
}


} // namespace voice
} // namespace harman
} // namespace com
} // namespace v0_1

